### ISSUE TITLE
Rename esxDOS file LOADER to LOADER.BAS

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [fjpena/sword-of-ianna-zx#1]
First of all: thank you and the team for such a fantastic polished game; the graphics, movement, playability and "complete package" experience is just top notch - bravo.

The other day someone shared about the esxDOS version that while in the instructions it says that it can be loaded with the NMI browser, it wouldn't. We found out that the default esxDOS NMI browser would indeed load the LOADER file, but Bob Fossil's Browse would not. When mentioning it in the Browse-dev forum, someone advised to rename it to LOADER.BAS instead.
And then indeed Browse will also load it.

Admittedly, one could also load it in BASIC, but when thinking about it, naming it .bas makes sense. Functionally, and also logically. People would instinctively load something with a .bas extension to load games, just as B files on TRD-DOS:

Could you rename the release version of the file on the website and also adapt the make-file accordingly?

**Comment by fjpena** [comment]
Thanks for the report! Actually, it makes sense to change that. 

I have had a look at the code (it's been a long time!) and I think I can do an easy fix. I'll try to get it done this week.

**Comment by TheStruggleForAntiSpaghetti** [comment]
I got a mail that the issue is solved :) 
Would it be a good idea to update the download package on the website too? (http://www.retroworks.es/php/download.php?file=ianna-esxdos-1_1.zip)

**Comment by fjpena** [comment]
I forgot to mention it, but the ZIP file in the website is already updates. Thanks!

**Comment by TheStruggleForAntiSpaghetti** [comment]
Good. Thank you :)
